#!/bin/sh
#
# Copyright (C) 2024 Mikulas Patocka
#
# This file is part of Ajla.
#
# Ajla is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Ajla is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Ajla. If not, see <https://www.gnu.org/licenses/>.

cd "`dirname $0`" || exit
rm -f *~
rm -rf *.o *.obj *.exe ajla
rm -f core
rm -f Makefile.am
rm -rf .deps Makefile config.cache config.h config.log config.status configure stamp-h1
rm -rf Makefile.in aclocal.m4 autom4te.cache config.h.in conftest* confdefs*
rm -f INSTALL config.guess config.sub depcomp install-sh missing
rm -f configure.lineno
rm -f .*.sw? */.*.sw? */*/.*.sw? */*/*/.*.sw? */*/*/*/.*.sw?
